### ISSUE TITLE
Add a way to ensure destructors are run

### ISSUE THREAD

**Issue by Others** [Others/shredder#17]
The API should probably look something like this:
```rust
fn main() {
     shredder::with_cleanup(|| {
         // Your code goes here
     })
}
```
Implementation notes:
- First modify the drop thread to have a "catch up message"
- Then cleanup needs to just run the closure, then collect, then submit a "catch up message"

**Comment by Others** [comment]
`run_with_gc_cleanup` is as good as we're gonna get :)

**Comment by StevenDoesStuffs** [comment]
@Others Maybe an attribute macro (like the ones they have for async) would work better? 
```rust
#[shredder::with_cleanup]
fn main() {
    // your code goes here
}
```
