### ISSUE TITLE
Add documentation to Collector

### ISSUE THREAD

**Issue by seanchen1991** [Others/shredder#30]
The `collector` module seems to be a fundamental part of the library, and also one of the largest modules in terms of SLOC. Some more comprehensive docs for it would probably streamline the learning process for this module.

**Comment by Others** [comment]
Related to #11, but focusing on code docs instead of high level documentation.

I will try and get around to adding comments, but if you have any specific questions I can try and address them here. (Or you can PM me on the Rust discord @Others)
